server:
  port: 4500
---
environment: prod
myCustomVarTree:
  welcomeMsg: Hello from Prod
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 5000
---
environment: test
myCustomVarTree:
  welcomeMsg: Hello from Test
spring:
  config:
    activate:
      on-profile: test
server:
  port: 4000
